### ISSUE TITLE
withLang problem

### ISSUE THREAD

**Issue by metaldave** [Anahkiasen/polyglot#1]
Don't know if is a bug or my inesperience (I'm new to laravel) but I can't use the withLang scope query, my execution of: 

```
Article::withLang()->get();
```

throw this error:

```
Class 'Polyglot\App' not found in /vendor/anahkiasen/polyglot/src/Polyglot/Polyglot.php at line 222
```

I thought it was a namespace problem, so I've changed (in my code) that line adding a _\_ before the _App:make_ call, so:

```
$eager = call_user_func_array(array(\App::make('polyglot.lang'), 'eager'), $relations);
```

but that code throw this other error: 

```
Class polyglot.lang does not exist
```

**Comment by Anahkiasen** [comment]
Should be fixed on latest, can you update and tell me if it's still here ?

**Comment by metaldave** [comment]
yep, now it works, thank you!
