### ISSUE TITLE
Throws NotFoundHttpException

### ISSUE THREAD

**Issue by taai** [Anahkiasen/polyglot#15]
I did everything like in README, but it gives me an `NotFoundHttpException` error. It's not caused by anything else, because it runs when I remove `Polyglot\PolyglotServiceProvider` from `providers` list in `app.php` file.

I did find that if I uncomment these lines ( https://github.com/Anahkiasen/polyglot/blob/master/src/Polyglot/PolyglotServiceProvider.php#L82-84 ) the error disappears, so I guess there is something wrong with your `Router` implementation...

I'm using the latest Laravel 4.1.17

**Comment by taai** [comment]
The routes are being wiped out. It turns out that you have to add the `Polyglot\PolyglotServiceProvider` in `providers` list **before** the `Illuminate\Routing\ControllerServiceProvider` and then it works.

Please, find out how to make this independent of the order in `providers` list! Or at least write this finding in the readme file!

**Comment by Anahkiasen** [comment]
I've never had problems with that no matter what the order of the providers. I just tested on 4.1.17 and it worked fine. Can you show me your `routes.php` file ?

**Comment by AlexRegenbogen** [comment]
Just my quick 2 cents:

Ran into this one myself just now, traced it to codesleeve/asset-pipeline.
If 'Polyglot\PolyglotServiceProvider', is located after that line, it's NotFoundHttpException, if just above that line, no problem....

My routes.php has nothing to do with it, i'm sure...no other routes that the ones L4 came with ;-)
(setting up a new codebase for our application, and trying out stuff on a pristene L4 installation.)

Hope this send you in the right direction.

**Comment by Anahkiasen** [comment]
Will reopen if this is still occurring.
