### ISSUE TITLE
Trait

### ISSUE THREAD

**Issue by casoetan** [Anahkiasen/polyglot#17]
Is it possible to use this as a trait on the model class. My models already extend Ardent and php not being a single inheritance language. 
Just wanted to know it can be updated to be used as a trait in my models freeing me to extend other classes like Ardent.

**Comment by casoetan** [comment]
Hello @Anahkiasen any update on this anytime soon? Thanks

**Comment by taai** [comment]
@casoetan I would like to use traits too. Traits are being supported by PHP 5.4 and newer versions. Polyglot could have the trait support as opt-in, or, just live on by forgetting PHP 5.3 support...

**Comment by casoetan** [comment]
@taai lets start it as an opt-in feature, but gradually nudge users towards 5.4+. 

Thanks for the response.

**Comment by Anahkiasen** [comment]
The problem is it can't be opt-in unless I copy/paste all the code from the model to the trait.

**Comment by casoetan** [comment]
What about a new branch for 5.4 dev?

**Comment by Anahkiasen** [comment]
This will be done for 2.0.0 which will be 5.4+

**Comment by casoetan** [comment]
thanks, any ETAs yet?

Sent with Mail Pilot

**Comment by Anahkiasen** [comment]
Not really, I've almost finished the gettext module of 2.0 on the develop branch which allows you to extract/compile translations from the available views but I haven't started work on the database part of Polyglot yet.

**Comment by Anahkiasen** [comment]
Done on the develop branch, can use `2.0.*@dev` to try it out

**Comment by casoetan** [comment]
Thanks
