### ISSUE TITLE
Undefined method error in combination with modulemanager

### ISSUE THREAD

**Issue by dipsynl** [Anahkiasen/polyglot#2]
When i use this package with LevareCMS/modulemanager and make this call in a routes.php placed in a module folder: 

Route::groupLocale(array('before' => ''), function() {

```
Route::get('/', function()
{
    return 'Hello world';
});
```

});

I get the following error:
Call to undefined method Illuminate\Translation\Translator::valid()
/­vendor/­anahkiasen/­polyglot/­src/­Polyglot/­Router.php line 44

**Comment by Anahkiasen** [comment]
Hm yes that actually makes sense : both package overwrite the Translator, there can be only one. I'll see what I can do to decouple it a little bit so that the Router can talk to the Polyglot classes event if it isn't the main Translator.

**Comment by Anahkiasen** [comment]
Polyglot now has a `facade` option to disable overriding the main facades, if you'd rather have another package do that
