### ISSUE TITLE
Call to undefined method ContentLang::newQuery()

### ISSUE THREAD

**Issue by abbasadel** [Anahkiasen/polyglot#23]
Hi,

I'm getting this error message. Any ideas?

Call to undefined method ContentLang::newQuery()

Thanks,
Abbas

**Comment by Anahkiasen** [comment]
When doing what more exactly ?

**Comment by abbasadel** [comment]
I created a a table contents and content_lang as below.

```
contents: id, active, created_at, updated_at
content_lang: id, title, body, content_id, lang
```

 When I try to create a new Content, 

```
    Content::create(['title'=>'test', 'body'=>'test', 'lang'=>'en']);
```

I got this error

```
    Call to undefined method ContentLang::newQuery()
```

Any recommendations? 
Thanks a lot @Anahkiasen. Great work BTW

**Comment by Anahkiasen** [comment]
You should have:
- Content extending Polyglot
- ContentLang extending Eloquent

is that correct ?

**Comment by abbasadel** [comment]
Exactly. I followed the provided instructions.

**Comment by abbasadel** [comment]
I found the problem. I had a migration with the name ContentLang which made a conflict.

Thanks a lot.
