### ISSUE TITLE
Not work under Workbench

### ISSUE THREAD

**Issue by alvaro-canepa** [Anahkiasen/polyglot#24]
I have the models Content and ContentLang (http://pastebin.com/725xtXex)
I made the "composer dump-autoload"
But when I try to access to the main package "Teros/Content" (using Orchestra Platform) I  get "Class 'ContentLang' not found". 
I need to create a Facade for the model ContentLang too?

**Comment by alvaro-canepa** [comment]
I still have this problem. Any help?

thanks

**Comment by fiveanddone** [comment]
This is an old post but I ran into something similar.

I was able to get my test working by following this link:

https://github.com/laravel/framework/issues/1181

**Comment by Anahkiasen** [comment]
Will reopen if this is still occurring.
