### ISSUE TITLE
Incompatibility with Indonesian (when based on the ISO 639-1 spec)

### ISSUE THREAD

**Issue by cilyaa** [Anahkiasen/polyglot#35]
This is a just a quick "heads up" as i've encountered this problem recently. I don't know whether it should be considered a bug, as it is inherent to the ISO 639-1 specification and the way Polyglot works.

The ISO 639-1 defines language as 2-letters codes. In this spirit, indonesian is defined with the code **"id"**.

Obviously, this messes up Polyglot quiet a bit. For example, querying a Polyglotted model via Eloquent for its **id** (as in the primary key) doesn't work, because it tries to deliver some indonesian string...

I guess, in fewer words, ISO 639-1 adopters', beware of the indonesian conundrum...

**Comment by Anahkiasen** [comment]
Well you can use whatever you want as the lang handle so you can use the long ISO code no?
