### ISSUE TITLE
problem saving models

### ISSUE THREAD

**Issue by mhddurrah** [Anahkiasen/polyglot#37]
I have a "car" model
<code>class Car extends Polyglot </code>
<code>class CarLang extends Model </code>

the car contains protected $polyglot = ['name', 'description'];

saving car name and desc using
<code>$car->fill() </code> causes a <code> MassAssignmentException</code>
using <code>$car->ar->fill([]);</code> causes <code> Call to a member function fill() on a non-object </code>

any ides please?

**Comment by Anahkiasen** [comment]
Well is the field fillable ?

**Comment by zanthrax** [comment]
The CarLang model should probably extend the Eloquent class.

To prevent the MassAssignment Exception add a protected $fillable property to you CarLang Class, this property should contain every column name in your car_lang DB table except for the id column.
Check the Laravel Docs on Mass Assignment to see why you need a $fillable property.
http://laravel.com/docs/eloquent#mass-assignment

I'd also like to know how to fix the 'Call to a member function fill() on a non-object' errors. I can't get Polyglot to create all translations lines in the database automatically. None of the variations of using the fill() function seem to work when creating new items, only on items with existing translations in the DB.

**Comment by mhddurrah** [comment]
this is the car class
![car](https://cloud.githubusercontent.com/assets/3740671/2764617/ea5fb1b0-ca17-11e3-9803-2bb700151ade.png)
and this is the CarLang class
![carlang](https://cloud.githubusercontent.com/assets/3740671/2764623/f2d5a3d6-ca17-11e3-8975-6037f8f51706.png)

this is the test case (with route)
![test](https://cloud.githubusercontent.com/assets/3740671/2764624/009f85fe-ca18-11e3-84de-0a62f228a83d.png)

but still find the same issue
![res](https://cloud.githubusercontent.com/assets/3740671/2764627/0738f36e-ca18-11e3-842f-e294e41bc41a.png)

**Comment by zanthrax** [comment]
Does adding
    protected $fillable = [’name’, ‘description’, ‘lang’];
to the Car class help?
$car->fill() mass assigns to an instance of the Car class, Polyglot passes the data on to the CarLang class, so AFAIK both need to be set up for mass assignment.

**Comment by mhddurrah** [comment]
@zanthrax Thanks
I get the following when adding fillable
![screenshot_3](https://cloud.githubusercontent.com/assets/3740671/2774196/7b26f19c-cab1-11e3-8b55-9ba7c46563f7.png)

**Comment by zanthrax** [comment]
That one's pretty self-explanatory and not related to Polyglot.
http://laravel.com/docs/eloquent#timestamps

**Comment by mhddurrah** [comment]
https://www.dropbox.com/sh/v818gvtwf66cd1s/f3mHOs_1BH
with these structure and using fill method of car the relation between Car and CarImage not created
I get the error  Integrity constraint violation: 1048 Column 'car_id' cannot be null (SQL: insert into `car_images` (`file_name`, `car_id`) values (image, )) 
but when commenting the fill method I get the relation and image saved with the right foreign key

**Comment by zanthrax** [comment]
car_id probably needs to be in the car_lang fillable property. I'm just guessing, based on info I gave before and the error your code gives.
Another non-polyglot-related hint: model relations only need a table- and column name if they differ from regular Laravel names. Most of yours don't.

**Comment by mhddurrah** [comment]
the problem still found. only for saving
when using <code>$car->fill </code> it gives that car_id is null
when using <code>$car->en->fill</code> it says fill on non-object
it is a horrible feel to face this problem and should be documented well
I solved it by creating CarLang objects manually and save them.
thanks

**Comment by Anahkiasen** [comment]
Will reopen if this is still occurring.
