### ISSUE TITLE
Throws exception for route groups with prefixes

### ISSUE THREAD

**Issue by ckhampus** [Anahkiasen/polyglot#38]
With following code:

``` php
Route::groupLocale(array(
    'prefix' => 'group',
), function () {
    // code ...
});
```

I get the following exception:

```
ErrorException
trim() expects parameter 1 to be string, array given
```

The prefix returned by the Polyglot router looks like this:

```
array (size=2)
  0 => string 'en' (length=2)
  1 => string '{group}' (length=7)
```

though it should probably look like this:

```
string 'en/{group}' (length=10)
```

I’m using the `develop` branch and Laravel 4.1.

**Comment by Anahkiasen** [comment]
I think passing an array as prefix used to work on the old Routing based on symfony but not anymore. Pushed a fix, can you check ?

**Comment by Anahkiasen** [comment]
Will reopen if this is still occurring.
