### ISSUE TITLE
"switchLanguage" on homepage without trailing slash

### ISSUE THREAD

**Issue by thomaspaillot** [Anahkiasen/polyglot#4]
Hi,

The "switchLanguage" function doesn't work as expected when I'm on the index of my site. When I'm on http://domain.com/fr and I switch to english, the url becomes http://domain.com/fr/en. It's because the regex in the function try to find 2 letters between slash and when you have just one segment with the prefix with nothing after, there is no trailing slash so the language prefix isn't replace.

Do you have a quick solution to fix this ? I tried to fix it myself but it didn't work out for the moment.

Thanks

**Comment by Anahkiasen** [comment]
Should be fixed.

**Comment by thomaspaillot** [comment]
Merci !
