### ISSUE TITLE
Soft deletes in Laravel 4.2 + Polyglot

### ISSUE THREAD

**Issue by mark-janssen** [Anahkiasen/polyglot#43]
After updating my project to Laravel 4.2 my models that use Polyglot no longer can be deleted.
The deleted_at DB column is filled on delete but when fetching rows using Eloquent deleted items are also returned with my regular results.
Soft delete is working for Models that extend Eloquent instead of Polyglot.
Has anyone been able to get Polyglot to work with softdeletes in L4.2?
I can't even back out of this update using composer. Before my update I used the dev-develop Polyglot release on Laravel 4.1.\* but Composer will not install that combination anymore.

```
 - anahkiasen/polyglot dev-develop requires illuminate/container ~4.2
```

An example class:

```
<?php

use Polyglot\Polyglot;

class Productgroup extends Polyglot {

    use SoftDeletingTrait;

    //protected $fillable = ['id', 'parent_id', 'image', 'order_by'];    
    protected $polyglot = ['name', 'description', 'promo_text'];
    public $imgFolder = 'productgroups/';
    protected $appends = ['productCount'];
    protected $dates = ['deleted_at'];

    public function imgUrl() {
        return Config::get('app.url') . 'public/' . Config::get('path.uploads') . $this->imgFolder . $this->image;
    }

    ....
```

I have added 'SoftDeletingTrait' => 'Illuminate\Database\Eloquent\SoftDeletingTrait', to my aliases in /app/config/app.php

**Comment by AlexRegenbogen** [comment]
Try adding this below you use Polyglot\Polyglot: 
use Illuminate\Database\Eloquent\SoftDeletingTrait;

**Comment by Anahkiasen** [comment]
Will reopen if this is still occurring.
