### ISSUE TITLE
How to reduce repeating $fillable attributes in Polyglot package?

### ISSUE THREAD

**Issue by esomkin** [Anahkiasen/polyglot#47]
Hi, Maxime!

Recently I'am start using your package Polyglot and it very interest of me. As I understand, to correct working with package need to create at least two models, for exampe Article and ArticleLang.

```
class Article extends Polyglot
{
    protected $fillable = [

        'url',
        'name',
        'title',
    ];

    protected $polyglot = [

        'name',
        'title',
    ];
}
```

and

```
class ArticleLang extends Model
{
    public $timestamps = false;

    protected $fillable = [

        'name',
        'title',
    ];
}
```

As you can see, there are many repeatings in $fillable and $polyglot attributes. If I delete some parameters, I see MassAssingment exception.

How do you think, is there any way to reduce repeatings of field names or I do something wrong ?

**Comment by Anahkiasen** [comment]
Override `getPolyglotAttribute`

``` php
public function getPolyglotAttributes()
{
  return array_merge($this->fillable, ['lang']);
}
```
