### ISSUE TITLE
L5 support?

### ISSUE THREAD

**Issue by uldisrudzitis** [Anahkiasen/polyglot#49]
L5 support?

**Comment by ivandokov** [comment]
+1

**Comment by berta-cms** [comment]
alternative: https://github.com/vinkla/translator

**Comment by ivandokov** [comment]
@berta-cms looks good. Will try it for sure!

**Comment by Anahkiasen** [comment]
L5 support is being worked on in the develop branch, can require `anahkiasen/polyglot:2.0.*@dev` to try it out.
