### ISSUE TITLE
Saving translated content

### ISSUE THREAD

**Issue by nWidart** [Anahkiasen/polyglot#7]
Hello,

I can't seem to understand how to use of this package. I've tried different alternatives, always returns an error.

I'm trying to translate a "portfolio" model:

```
<?php namespace Nwidart\Portfolio\Models;

class PortfolioItem extends BaseModel
{
    protected $polyglot = ['title', 'content', 'slug'];
}
```

And it's -Lang table:

```
<?php namespace Nwidart\Portfolio\Models;

use Polyglot\Polyglot;

class PortfolioItemLang extends Polyglot
{
    protected $guarded = array('id');
    protected $table = 'PortfolioItem_Lang';
}
```

My controller:

```
<?php namespace Nwidart\Portfolio\Controllers\Admin;

use Nwidart\Portfolio\Models\PortfolioItemLang;
use Nwidart\Portfolio\Services\Validators\PortfolioItem as PortfolioItemValidator;
use View;
use Input;
use Platform\Admin\Controllers\Admin\AdminController;
use Nwidart\Portfolio\Models\PortfolioItem;

class PortfolioController extends AdminController
{
[...]
public function postCreate()
    {
        $v = new PortfolioItemValidator();

        $portfolioItem = new PortfolioItemLang();

        $portfolioItem->fill([
            'title'   => Input::get('title'),
            'content' => Input::get('description'),
            'lang' => 'fr'
        ])->save();
    }
```

Thank you

**Comment by Anahkiasen** [comment]
It's the other way around, your base model needs to extend Polyglot while the Lang model needs to be a basic Eloquent model. Does that work ?

**Comment by nWidart** [comment]
Ah ok. Switched the extended classes around.
No errors on save, the content (title & description) are saved correctly.
One thing though, the portfolioItem_id column wasn't set. Do we have to set it manually in some way, or ? :)

Thank you,

**Comment by nWidart** [comment]
Hello, 

I don't know if you've seen, but I've edited the previous post, asking if it was normal the the foreign key wasn't set (portfolioItem_id).

Thank you,

**Comment by Anahkiasen** [comment]
Ok sorry for the delay. The key isn't set automatically, at least not by Polyglot. It is set automatically however when using Eloquent relations, that's because you're not doing that at the moment.

That means instead of this :

``` php
$portfolioItem = new PortfolioItemLang();

$portfolioItem->fill([
  'title'   => Input::get('title'),
  'content' => Input::get('description'),
  'lang' => 'fr'
])->save();
```

What you want to do is this :

``` php
$portfolioItem = new PortfolioItem();

$portfolioItem->fr->fill([
  'title'   => Input::get('title'),
  'content' => Input::get('description'),
])->save();
```

I just tested it on a fresh Laravel application and that will work.
