### ISSUE TITLE
URL::locale function doesn't return the default locale when the url doesn't contains it

### ISSUE THREAD

**Issue by thomaspaillot** [Anahkiasen/polyglot#8]
When you choose to didn't add a locale prefix on your default language url (like in, http://mysite.com/contact, I don't put 'fr' in the url) the URL::locale function will not return your default locale string but instead the first segment of the url, in my exemple "contact".

**Comment by Anahkiasen** [comment]
That's normal, `URL::locale` is just here to tell you if you have a locale in your URL and return it, nothing else. If you want the current language you want to use the methods on the `Lang` class.
